sybinit.charset: iso_1
sybinit.language: us_english
sybinit.component_directory: /ccs/repsrv15_0/REP-15_0
sybinit.release_directory: /ccs/repsrv15_0
sybinit.boot_directory: /ccs/repsrv15_0
sybinit.product: rs
sqlsrv.sa_password: USE_DEFAULT
sqlsrv.sa_login: USE_DEFAULT
sqlsrv.master_device_size: USE_DEFAULT
sqlsrv.master_device_physical_name: USE_DEFAULT
sqlsrv.server_name: USE_DEFAULT
sqlsrv.new_config: USE_DEFAULT
rs.rs_db_active_sa_pw: 63vette 
rs.rs_db_active_sa: cron_sa
rs.rs_db_active_db_name: PartyMember
rs.rs_db_active_ds_name: w151dbp02
rs.rs_db_use_dmp_marker: yes
rs.rs_db_logical_db_name: PartyMember
rs.rs_db_logical_ds_name: LogicalSRV
rs.rs_db_active_or_standby: standby
rs.rs_db_physical_for_logical: yes
rs.rs_operation: rs_setup_db
rs.rs_db_maint_password: stickt0it
rs.rs_db_maint_user: w151rep02_maint_user
rs.rs_db_name: PartyMember
rs.rs_ds_sa_password: 63vette
rs.rs_ds_name: w151dbp05
rs.rs_needs_repagent: yes
rs.rs_requires_ltm: no
rs.do_add_ltm: no
rs.rs_ltm_rs_pass: stickt0it
rs.rs_ltm_rs_user: w151rep02_ra_user
rs.rs_rs_sa_pass: stickt0it
rs.rs_name: w151rep02
# -END_ATTRIBUTES-
