##./Online_update_index_statistics.sh v151dbp01ivr atlLL
./Online_update_index_statistics.sh v151dbp01ivr bosLL
./Online_update_index_statistics.sh v151dbp01ivr calLL
./Online_update_index_statistics.sh v151dbp01ivr chdLL
./Online_update_index_statistics.sh v151dbp01ivr chiLL
./Online_update_index_statistics.sh v151dbp01ivr chrLL
./Online_update_index_statistics.sh v151dbp01ivr colLL
./Online_update_index_statistics.sh v151dbp01ivr dalLL
./Online_update_index_statistics.sh v151dbp01ivr defLL
./Online_update_index_statistics.sh v151dbp01ivr detLL
./Online_update_index_statistics.sh v151dbp01ivr dnrLL
./Online_update_index_statistics.sh v151dbp01ivr edmLL
./Online_update_index_statistics.sh v151dbp01ivr gbrLL
./Online_update_index_statistics.sh v151dbp01ivr harLL
./Online_update_index_statistics.sh v151dbp01ivr idpLL
./Online_update_index_statistics.sh v151dbp01ivr laxLL
./Online_update_index_statistics.sh v151dbp01ivr milLL
./Online_update_index_statistics.sh v151dbp01ivr minLL
./Online_update_index_statistics.sh v151dbp01ivr mtlLL
./Online_update_index_statistics.sh v151dbp01ivr nsvLL
./Online_update_index_statistics.sh v151dbp01ivr nycLL
./Online_update_index_statistics.sh v151dbp01ivr ottLL
./Online_update_index_statistics.sh v151dbp01ivr parLL
./Online_update_index_statistics.sh v151dbp01ivr phiLL
./Online_update_index_statistics.sh v151dbp01ivr phnLL
./Online_update_index_statistics.sh v151dbp01ivr pitLL
./Online_update_index_statistics.sh v151dbp01ivr potLL
./Online_update_index_statistics.sh v151dbp01ivr qstLL
./Online_update_index_statistics.sh v151dbp01ivr seaLL
./Online_update_index_statistics.sh v151dbp01ivr sfoLL
./Online_update_index_statistics.sh v151dbp01ivr stlLL
./Online_update_index_statistics.sh v151dbp01ivr torLL
./Online_update_index_statistics.sh v151dbp01ivr uscLL
./Online_update_index_statistics.sh v151dbp01ivr vanLL
./Online_update_index_statistics.sh v151dbp01ivr wasLL
./Online_update_index_statistics.sh v151dbp01ivr winLL
