create replication definition "qstLL_Mailbox"
with primary at LogicalSRV.qstLL
with all tables named "Mailbox"
(
                "region" int,                                                   
                "boxnum" int,                                                   
                "adnum" as "adNum" int,                                                    
                "greetingnum" as "greetingNum" int,                                              
                "accountnum" int,                                               
                "status" int,                                                   
                "rcac" int,                                                     
                "passcode" int,                                                 
                "gender" int,                                                   
                "date_created" as "dateCreated" datetime,                                        
                "date_lastaccess" as "dateLastAccess" datetime,                                     
                "ani" char(25),                                                 
                "cf_status" as "cfStatus" int,                                                
                "mp_status" as "mpStatus" int,                                                
                "phonenum" as "phoneNum" char(10),                                            
                "ad_status" as "adStatus" int,                                                
                "ad_autoapprove" as "adAutoApprove" int,                                           
                "ad_segment" as "adSegment" int,                                               
                "ad_category" as "adCategory" int,                                              
                "date_ad" as "dateAd" datetime,                                             
                "date_birth" as "dateBirth" datetime,                                          
                "age" int,                                                      
                "burb" int,                                                     
                "language" int,                                                 
                "top100" int,                                                 
                "www" int,
                "onlineStatus" int,                                             
                "cf_start" as "cfStart" int,                                                 
                "cf_end" as "cfEnd" int,                                                   
                "cf_count" as "cfCount" int,                                                 
                "gr_status" as "grStatus" int,                                                
                "gr_date_created" as "grDateCreated" datetime,                                     
                "body" int,
                "looks" int,
                "height" int,
                "ethnicity" int,                                                
                "picture" int,                                                  
                "filter" int,                                                   
                "login_count" as "loginCount" int,                                              
                "partnershipId" int,                                            
                "dnis" char(25),                                                
                "hltaCounter" int,                                              
                "sc_member" as "scMember" int,                                             
                "daCaller" int,                                                 
                "cellPhonenum" as "cellPhoneNum" char(10),                                  
                "mt_start"  as "mtStart" int,                                                 
                "mt_end" as "mtEnd" int,                                                   
                "postcode" as "postCode" char(20),                                            
                "lat_rad" as "latRad" int,                                                  
                "long_rad" as "longRad" int,                                                 
                "rcac_member" as "rcacMember" int,                                              
                "accountregion" as "accountRegion" int,                                            
                "accountId" int,                                                
                "serialNumber" as "mailboxId" int,                                             
                "searchRadiusMiles" int,                                        
                "picture_status" as "pictureStatus" int ,                                          
                "adDnis" char(25),                                              
                "adId" int,
                "greetingId" int,
                "ethnicLanguage" int,                                           
                "postcode_prefix" as "postCodePrefix" char(6),                                      
                "daLastCallBackReminder" datetime                               
)
primary key ("serialNumber")
replicate minimal columns
/* No searchable columns */
/* No minimal columns */

go

