srvbuild.release_directory: /opt/sybase
srvbuild.product: sqlsrv
srvbuild.server_name: w151dbp10
srvbuild.new_config: yes
srvbuild.do_add_server: yes
srvbuild.do_upgrade: no
srvbuild.network_protocol_list: tcp
srvbuild.network_hostname_list: w151dbp10
srvbuild.network_port_list: 8100
srvbuild.application_type: OLTP
srvbuild.server_page_size: 2k
srvbuild.master_device_physical_name: /data/syb_db/w151dbp10/master.dat
srvbuild.master_device_size: 200
srvbuild.master_database_size: 100
srvbuild.errorlog: /opt/sybase/ASE-15_0/install/logs/w151dbp10.log
srvbuild.sybsystemprocs_device_physical_name: /data/syb_db/w151dbp10/sysprocs.dat
srvbuild.sybsystemprocs_device_size: 200
srvbuild.sybsystemprocs_database_size: 200
srvbuild.sybsystemdb_device_physical_name: /data/syb_db/w151dbp10/sybsysdb.dat
srvbuild.sybsystemdb_device_size: 200
srvbuild.sybsystemdb_database_size: 200
srvbuild.tempdb_device_physical_name: /data/syb_db/w151dbp10/tempdbdev.dat
srvbuild.tempdb_device_size: 2000
srvbuild.tempdb_database_size: 2000
srvbuild.default_backup_server: w151dbp10_BS
srvbuild.addl_cmdline_parameters: 
srvbuild.do_configure_pci: no
srvbuild.sybpcidb_device_physical_name: /opt/sybase/data/sybpcidbdev_data.dat
srvbuild.sybpcidb_device_size: 48
srvbuild.sybpcidb_database_size: 48
srvbuild.do_optimize_config: yes
srvbuild.avail_physical_memory: 2000
srvbuild.avail_cpu_num: 2
