/* This Isql script was generated by rec_index.pl on Mon Apr 21 09:10:00 2003.  */

use Profile_ai
go
declare @getdate datetime
select @getdate=getdate()

DROP INDEX Smile.XPKSmile

IF NOT EXISTS (SELECT * FROM sysindexes WHERE id=OBJECT_ID('dbo.Smile') AND name='XPKSmile')
PRINT '<<<<<< %1! Index dbo.Smile.XPKSmile Drop SUCCEEDED!!! >>>>>>',@getdate
ELSE
PRINT '<<<<<<< %1! Index dbo.Smile.XPKSmile Drop FAILED!!! >>>>>>>',@getdate
go

declare @getdate datetime
select @getdate=getdate()

CREATE UNIQUE CLUSTERED INDEX XPKSmile
ON dbo.Smile (userId ASC, targetUserId ASC)
IF EXISTS (SELECT * FROM sysindexes WHERE id=OBJECT_ID('dbo.Smile') AND name='XPKSmile')
PRINT '<<<<<< %1! Index dbo.Smile.XPKSmile Creation SUCCEEDED!!! >>>>>>',@getdate
ELSE
PRINT '<<<<<<< %1! Index dbo.Smile.XPKSmile Creation FAILED!!! >>>>>>>',@getdate
go
