IF OBJECT_ID('DeferredRev.PositiveChartJul2005') IS NOT NULL
BEGIN
   DROP TABLE DeferredRev.PositiveChartJul2005
END
ELSE BEGIN
   PRINT 'THERE IS NO TABLE DeferredRev.PositiveChartJul2005' 
END
go
CREATE TABLE DeferredRev.PositiveChartJul2005
(
  userId              numeric(12,0) NOT NULL
, dateLastPurchased      datetime      NULL
, initialBalance         int           NULL
, creditLastPurchased    int           NULL
, creditConsumedD1 int NULL  
, creditConsumedD2 int NULL  
, creditConsumedD3 int NULL  
, creditConsumedD4 int NULL  
, creditConsumedD5 int NULL  
, creditConsumedD6 int NULL  
, creditConsumedD7 int NULL  
, creditConsumedD8 int NULL  
, creditConsumedD9 int NULL  
, creditConsumedD10 int NULL  
, creditConsumedD11 int NULL  
, creditConsumedD12 int NULL  
, creditConsumedD13 int NULL  
, creditConsumedD14 int NULL  
, creditConsumedD15 int NULL  
, creditConsumedD16 int NULL  
, creditConsumedD17 int NULL  
, creditConsumedD18 int NULL  
, creditConsumedD19 int NULL  
, creditConsumedD20 int NULL  
, creditConsumedD21 int NULL  
, creditConsumedD22 int NULL  
, creditConsumedD23 int NULL  
, creditConsumedD24 int NULL  
, creditConsumedD25 int NULL  
, creditConsumedD26 int NULL  
, creditConsumedD27 int NULL  
, creditConsumedD28 int NULL  
, creditConsumedD29 int NULL  
, creditConsumedD30 int NULL  
, creditConsumedD31 int NULL  
, creditConsumedD32 int NULL  
, creditConsumedD33 int NULL  
, creditConsumedD34 int NULL  
, creditConsumedD35 int NULL  
, creditConsumedD36 int NULL  
, creditConsumedD37 int NULL  
, creditConsumedD38 int NULL  
, creditConsumedD39 int NULL  
, creditConsumedD40 int NULL  
, creditConsumedD41 int NULL  
, creditConsumedD42 int NULL  
, creditConsumedD43 int NULL  
, creditConsumedD44 int NULL  
, creditConsumedD45 int NULL  
, creditConsumedD46 int NULL  
, creditConsumedD47 int NULL  
, creditConsumedD48 int NULL  
, creditConsumedD49 int NULL  
, creditConsumedD50 int NULL  
, creditConsumedD51 int NULL  
, creditConsumedD52 int NULL  
, creditConsumedD53 int NULL  
, creditConsumedD54 int NULL  
, creditConsumedD55 int NULL  
, creditConsumedD56 int NULL  
, creditConsumedD57 int NULL  
, creditConsumedD58 int NULL  
, creditConsumedD59 int NULL  
, creditConsumedD60 int NULL  
, creditConsumedD61 int NULL  
, creditConsumedD62 int NULL  
, creditConsumedD63 int NULL  
, creditConsumedD64 int NULL  
, creditConsumedD65 int NULL  
, creditConsumedD66 int NULL  
, creditConsumedD67 int NULL  
, creditConsumedD68 int NULL  
, creditConsumedD69 int NULL  
, creditConsumedD70 int NULL  
, creditConsumedD71 int NULL  
, creditConsumedD72 int NULL  
, creditConsumedD73 int NULL  
, creditConsumedD74 int NULL  
, creditConsumedD75 int NULL  
, creditConsumedD76 int NULL  
, creditConsumedD77 int NULL  
, creditConsumedD78 int NULL  
, creditConsumedD79 int NULL  
, creditConsumedD80 int NULL  
, creditConsumedD81 int NULL  
, creditConsumedD82 int NULL  
, creditConsumedD83 int NULL  
, creditConsumedD84 int NULL  
, creditConsumedD85 int NULL  
, creditConsumedD86 int NULL  
, creditConsumedD87 int NULL  
, creditConsumedD88 int NULL  
, creditConsumedD89 int NULL  
, creditConsumedD90 int NULL  
, creditConsumedD91 int NULL  
, creditConsumedD92 int NULL  
, creditConsumedD93 int NULL  
, creditConsumedD94 int NULL  
, creditConsumedD95 int NULL  
, creditConsumedD96 int NULL  
, creditConsumedD97 int NULL  
, creditConsumedD98 int NULL  
, creditConsumedD99 int NULL  
, creditConsumedD100 int NULL  
, creditConsumedD101 int NULL  
, creditConsumedD102 int NULL  
, creditConsumedD103 int NULL  
, creditConsumedD104 int NULL  
, creditConsumedD105 int NULL  
, creditConsumedD106 int NULL  
, creditConsumedD107 int NULL  
, creditConsumedD108 int NULL  
, creditConsumedD109 int NULL  
, creditConsumedD110 int NULL  
, creditConsumedD111 int NULL  
, creditConsumedD112 int NULL  
, creditConsumedD113 int NULL  
, creditConsumedD114 int NULL  
, creditConsumedD115 int NULL  
, creditConsumedD116 int NULL  
, creditConsumedD117 int NULL  
, creditConsumedD118 int NULL  
, creditConsumedD119 int NULL  
, creditConsumedD120 int NULL  
, creditConsumedD121 int NULL  
, creditConsumedD122 int NULL  
, creditConsumedD123 int NULL  
, creditConsumedD124 int NULL  
, creditConsumedD125 int NULL  
, creditConsumedD126 int NULL  
, creditConsumedD127 int NULL  
, creditConsumedD128 int NULL  
, creditConsumedD129 int NULL  
, creditConsumedD130 int NULL  
, creditConsumedD131 int NULL  
, creditConsumedD132 int NULL  
, creditConsumedD133 int NULL  
, creditConsumedD134 int NULL  
, creditConsumedD135 int NULL  
, creditConsumedD136 int NULL  
, creditConsumedD137 int NULL  
, creditConsumedD138 int NULL  
, creditConsumedD139 int NULL  
, creditConsumedD140 int NULL  
, creditConsumedD141 int NULL  
, creditConsumedD142 int NULL  
, creditConsumedD143 int NULL  
, creditConsumedD144 int NULL  
, creditConsumedD145 int NULL  
, creditConsumedD146 int NULL  
, creditConsumedD147 int NULL  
, creditConsumedD148 int NULL  
, creditConsumedD149 int NULL  
, creditConsumedD150 int NULL  
, creditConsumedD151 int NULL  
, creditConsumedD152 int NULL  
, creditConsumedD153 int NULL  
, creditConsumedD154 int NULL  
, creditConsumedD155 int NULL  
, creditConsumedD156 int NULL  
, creditConsumedD157 int NULL  
, creditConsumedD158 int NULL  
, creditConsumedD159 int NULL  
, creditConsumedD160 int NULL  
, creditConsumedD161 int NULL  
, creditConsumedD162 int NULL  
, creditConsumedD163 int NULL  
, creditConsumedD164 int NULL  
, creditConsumedD165 int NULL  
, creditConsumedD166 int NULL  
, creditConsumedD167 int NULL  
, creditConsumedD168 int NULL  
, creditConsumedD169 int NULL  
, creditConsumedD170 int NULL  
, creditConsumedD171 int NULL  
, creditConsumedD172 int NULL  
, creditConsumedD173 int NULL  
, creditConsumedD174 int NULL  
, creditConsumedD175 int NULL  
, creditConsumedD176 int NULL  
, creditConsumedD177 int NULL  
, creditConsumedD178 int NULL  
, creditConsumedD179 int NULL  
, creditConsumedD180 int NULL  
)
go
