sybinit.charset: iso_1
sybinit.language: us_english
sybinit.component_directory: /opt/etc/repserver126/REP-12_6
sybinit.release_directory: /opt/etc/repserver126
sybinit.boot_directory: /opt/etc/repserver126
sybinit.product: rs
sqlsrv.sa_password: USE_DEFAULT
sqlsrv.sa_login: USE_DEFAULT
sqlsrv.master_device_size: USE_DEFAULT
sqlsrv.master_device_physical_name: USE_DEFAULT
sqlsrv.server_name: USE_DEFAULT
sqlsrv.new_config: USE_DEFAULT
rs.rs_db_physical_for_logical: no
rs.rs_operation: rs_setup_db
rs.rs_db_maint_password: stickt0it
rs.rs_db_maint_user: w151rep01_maint_user
rs.rs_db_name: Profile_ar
rs.rs_ds_sa_password: 63vette
rs.rs_ds_name: g151dbr07
rs.rs_rs_sa_pass: stickt0it
rs.rs_name: w151rep01
# -END_ATTRIBUTES-
